In [1]:
print("Hello, world!")

Hello, world!


# Define matrixs and make calculations
>>add and multiply included

In [10]:
import numpy as np

arr_a = np.array([[12, 15, 16],
                  [1, 23, 25],
                  [14, 5, 6]])
arr_b = np.array([[56, 54, 85],
                  [45, 47, 69],
                  [41, 21, 32]])

print('sum of elements of a=', np.sum(arr_a))
print('sum of elements of b=', np.sum(arr_b))

print('a*b=\n', arr_a * arr_b)
print('np.dot(a, b)=\n', np.dot(arr_a, arr_b))

print('The transpose of a=\n', np.transpose(arr_a))

sum of elements of a= 117
sum of elements of b= 450
a*b=
 [[ 672  810 1360]
 [  45 1081 1725]
 [ 574  105  192]]
np.dot(a, b)=
 [[2003 1689 2567]
 [2116 1660 2472]
 [1255 1117 1727]]
The transpose of a=
 [[12  1 14]
 [15 23  5]
 [16 25  6]]
